name: Build Electron + Streamlit (Windows)

on:
  push:
    branches: ["dev" ]
    tags:
      - 'v*'
    
jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # Checkout del codice
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Install Python deps in virtualenv
    - name: Install Python dependencies
      run: |
        python -m venv python_qlik
        python_qlik\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Install Node deps
    - run: npm ci

    # Workaround per evitare symlink su Windows
    - name: Disable symlinks
      run: setx npm_config_symlink false

    # Step custom del progetto

    - run: npm run app:dist
      env:
        PATH: python_qlik\Scripts;%PATH%

    # Calcolo versione
    - name: Set version
      run: |
        if ("${{ github.ref_name }}" -eq "dev") {
          $VERSION = "1.0.0-dev.${{ github.run_number }}"
        } else {
          $TAG = "${{ github.ref_name }}"
          $VERSION = $TAG -replace "^v", ""
        }
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV

        # aggiorna package.json con la nuova versione
        (Get-Content package.json) `
          -replace '"version":\s*".*?"', '"version": "' + $VERSION + '"' `
          | Set-Content package.json

    # Upload artifact se branch dev
    - name: Upload dev artifact
      if: github.ref_name == 'dev'
      uses: actions/upload-artifact@v4
      with:
        name: qlik-ops-${{ env.VERSION }}-win
        path: dist/qlik-ops-${{ env.VERSION}}-win.zip

    # Creazione release solo se tag
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ env.VERSION }}
        files: dist/qlik-ops-${{ env.VERSION}}-win.zip
