name: Build Electron + Streamlit (Windows)

on:
  push:
    branches: ["dev"]
    tags:
      - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # 1️⃣ Checkout del codice
    - uses: actions/checkout@v4

    # 2️⃣ Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 3️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # 4️⃣ Crea e popola il venv Python
    - name: Install Python dependencies
      run: |
        python -m venv python_qlik
        python_qlik\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 5️⃣ Install Node.js dependencies
    - run: npm ci

    # 6️⃣ Disabilita symlink su Windows (workaround)
    - name: Disable symlinks
      run: setx npm_config_symlink false

    # 7️⃣ Calcola versione dinamica in Python
    - name: Set version dynamically
      run: |
        python update_version.py

    # 8️⃣ Build Electron per Windows
    - name: Build Electron app
      run: npm run build:win
      env:
        PATH: python_qlik\Scripts;%PATH%

    # 9️⃣ Crea release GitHub
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: dist/Qlik-ops-${{ env.VERSION }}-win.zip
