name: Build Electron + Streamlit (Windows)

on:
  push:
    branches: ["dev" ]
    tags:
      - 'v*'
    
jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # Checkout del codice
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Install Python deps in virtualenv
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install --only-binary=:all: --target=python_embedded/Lib/site-packages -r requirements.txt
    - name: Test embedded Python import
      run: |
        ./python_embedded/python.exe -c "import sys; print(sys.path)"
        ./python_embedded/python.exe -c "import numpy; print('Numpy OK:', numpy.__version__)"
    # # Install Node deps
    - run: npm install
    - run: npm run app:dist

    # Workaround per evitare symlink su Windows
    - name: Disable symlinks
      run: setx npm_config_symlink false

    # Step custom del progetto


    # Calcolo versione dinamica
    - name: Set version
      run: |
        if ("${{ github.ref_name }}" -eq "dev") {
          $VERSION = "0.1.0-dev.${{ github.run_number }}"
        } elseif ("${{ github.ref_name }}" -eq "main") {
          $VERSION = "1.0.0"
        } elseif (startsWith("${{ github.ref_name }}", "v")) {
          $TAG = "${{ github.ref_name }}"
          $VERSION = $TAG -replace "^v", ""
        } else {
          $VERSION = "0.1.0-${{ github.run_number }}"
        }

        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
    # Aggiorna package.json usando Python
    - name: Update package.json version
      run: python update_version.py
    # Build app
    - run: npm run build:win
    # Creazione release sempre
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: dist/Qlik-ops-${{ env.VERSION}}-win.zip
